services:
  - type: web
    name: brain-tumor-predictor-api
    env: docker
    region: ohio
    plan: free
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8000
